// Code generated by cmd/sync-oss. DO NOT EDIT.
// This is a thin wrapper stub for the synclist product. Replace with
// hand-written logic when the product needs custom command handling.

package helpers

import (
	"github.com/spf13/cobra"
)

func newPatCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "pat",
		Short: "pat commands",
		Long:  "pat product commands (auto-generated stub).",
		RunE:  groupRunE,
	}
}
