// Code generated by cmd/sync-oss. DO NOT EDIT.
// Source: wukong.StaticServers() filtered by synclist.json

package syncdata

func StaticServers() []ServerInfo {
	return []ServerInfo{
		{ID: "agoal", Name: "Agoal", Endpoint: "https://mcp-gw.dingtalk.com/server/1db49ea94ffe74c25a7079a68b4df6629c79130fb9095d1b499f507015d847a9", Prefixes: []string{"agoal"}},
		{ID: "aisearch", Name: "AI 搜问", Endpoint: "https://mcp-gw.dingtalk.com/server/ai-search", Prefixes: []string{"aisearch", "enterprise"}},
		{ID: "aitable", Name: "AI 多维表", Endpoint: "https://mcp-gw.dingtalk.com/server/5f0d121611f14e878f7d42c3e32bf6c4a790d433066adae38c062a657c397047", Prefixes: []string{"table", "record", "field", "base", "attachment", "view", "dashboard", "chart", "export", "import"}},
		{ID: "aitable-helper", Name: "AI 多维表(辅助)", Endpoint: "https://mcp-gw.dingtalk.com/server/bb2984ee6b10c1560b4fe943ca620f646bed31f215c551a53abf040b52591a95", Prefixes: []string{"form", "share_form"}},
		{ID: "attendance", Name: "考勤打卡", Endpoint: "https://mcp-gw.dingtalk.com/server/72c8e63fa17cae0ea5bf507e2594d56c7b286122a747a9a28d4c30ac430cc774", Prefixes: []string{"attendance"}},
		{ID: "attendance-wukong", Name: "考勤打卡-悟空侧", Endpoint: "https://mcp-gw.dingtalk.com/server/6108af5ad4a429685416e98148a1d25b52ab88ffb680b12a7b3782c25b1a1150"},
		{ID: "bot", Name: "机器人消息", Endpoint: "https://mcp-gw.dingtalk.com/server/4717d5cbb92ecdebd89c174e4331dc17207208a97622e2004cac49c0fbedc9d1", Prefixes: []string{"bot", "robot"}},
		{ID: "calendar", Name: "日历", Endpoint: "https://mcp-gw.dingtalk.com/server/3cb83d4ac411227c44c1abde4e4bfbae0ea2c172b83a78a33ffc3821d0d1be47", Prefixes: []string{"calendar", "event"}},
		{ID: "chat", Name: "群聊/会话", Endpoint: "https://mcp-gw.dingtalk.com/server/0a1609437385696b77fc4771c3ddaf5656b487f809966c0cc8d4755e7b1d3b74", Prefixes: []string{"chat", "group"}},
		{ID: "contact", Name: "通讯录", Endpoint: "https://mcp-gw.dingtalk.com/server/db4b26cb38ea6a8739ad55d1997fa1da608cd36b33a6cf0f77884f70c49382fe", Prefixes: []string{"contact", "user", "dept"}},
		{ID: "devdoc", Name: "开放平台文档", Endpoint: "https://mcp-gw.dingtalk.com/server/47ec90fc0db1e68d84fdd2280129c219873b51e81a23adf9fe7fa29ee9b579b3", Prefixes: []string{"devdoc", "wiki"}},
		{ID: "ding", Name: "DING", Endpoint: "https://mcp-gw.dingtalk.com/server/404106cbb828de22de78bd390e7af4b2b24ec0cdc5088440ce10a41614fa328d", Prefixes: []string{"ding"}},
		{ID: "doc", Name: "文档", Endpoint: "https://mcp-gw.dingtalk.com/server/91e17caf44f6ca1ed9c6ce614221a518ac93300ece63ca8d7e9b133f912e0607", Prefixes: []string{"doc"}},
		{ID: "doc-comment", Name: "文档评论", Endpoint: "https://mcp-gw.dingtalk.com/server/doc-comment", Prefixes: []string{"doc-comment"}},
		{ID: "drive", Name: "钉盘", Endpoint: "https://mcp-gw.dingtalk.com/server/536f3b329ee774322b14361c666d6e9471e5bbb281b91ded8ca033b3ce7189af", Prefixes: []string{"drive"}},
		{ID: "hrmregister", Name: "智能人事", Endpoint: "https://mcp-gw.dingtalk.com/server/2494acfc37317871865c9c715664792200a52a89aeab58fee61cfc7262463c39", Prefixes: []string{"hrmregister"}},
		{ID: "im", Name: "im", Endpoint: "https://mcp-gw.dingtalk.com/server/450eede6b54d83e030140e66ec77c98a2e89a0869ef4db481f8217a98a42f821", Prefixes: []string{"im"}},
		{ID: "live", Name: "直播", Endpoint: "https://mcp-gw.dingtalk.com/server/57fb66889659c56df8f0a1838026b9004d8f4257fbef54fd04a028426253a033", Prefixes: []string{"live"}},
		{ID: "mail", Name: "邮箱", Endpoint: "https://mcp-gw.dingtalk.com/server/81395b96cfd92fd40858094064c1ed2f7f36eca3d7229d22aae426f74261a286", Prefixes: []string{"mail"}},
		{ID: "minutes", Name: "AI 听记", Endpoint: "https://mcp-gw.dingtalk.com/server/1e798e16a79e82eb7933050fbd58ed3ba8934170efb7c92565e39a1fb1c888e1", Prefixes: []string{"minutes"}},
		{ID: "oa", Name: "审批", Endpoint: "https://mcp-gw.dingtalk.com/server/8faff71bdfc3cb5437894ada5305b48214eb56408ca31e378f4be2773ba4500c", Prefixes: []string{"oa", "approval"}},
		{ID: "pat", Name: "行为授权", Endpoint: "https://mcp-gw.dingtalk.com/server/abc3c880fb90f04b52d1426aaf093766e5fc9ec38411688cbb74df42a584d374", Prefixes: []string{"pat"}},
		{ID: "report", Name: "钉钉日志", Endpoint: "https://mcp-gw.dingtalk.com/server/01d5a7b815babb03626bf3e505bad4c1e36ecf66876eaf6a7a466d9d5ccc9900", Prefixes: []string{"report"}},
		{ID: "sheet", Name: "钉钉表格", Endpoint: "https://mcp-gw.dingtalk.com/server/f7340bef5170f3baf97815989fc2bff68f4c293be82b2106c5d3e9cbbb14a17f", Prefixes: []string{"sheet"}},
		{ID: "todo", Name: "待办", Endpoint: "https://mcp-gw.dingtalk.com/server/0f51140eddcd913106c5821a4d0cd577b2d1a0b6cb452dd0e51ab41facf3a83c", Prefixes: []string{"todo", "task"}},
		{ID: "wiki", Name: "知识库", Endpoint: "https://mcp-gw.dingtalk.com/server/wiki", Prefixes: []string{"wiki"}},
	}
}
