// Code generated by cmd/sync-oss. DO NOT EDIT.
// Source: products.CmdToProduct() filtered by synclist.json

package syncdata

func CmdToProduct() map[string]string {
	return map[string]string{
		"agoal":      "agoal",
		"aisearch":   "aisearch",
		"aitable":    "aitable",
		"attendance": "attendance",
		"calendar":   "calendar",
		"chat":       "chat",
		"contact":    "contact",
		"devdoc":     "devdoc",
		"ding":       "ding",
		"doc":        "doc",
		"drive":      "drive",
		"live":       "live",
		"mail":       "mail",
		"minutes":    "minutes",
		"oa":         "oa",
		"pat":        "pat",
		"report":     "report",
		"sheet":      "sheet",
		"todo":       "todo",
		"wiki":       "wiki",
	}
}
