// Package syncdata holds the wukong product registry, synced from dws-wukong.
// Files in this package (except this one) are generated by cmd/sync-oss.
//
// Generated files call into wukong functions directly at generation time,
// so the data is always consistent with wukong's runtime behaviour.
package syncdata

// ServerInfo describes one MCP server endpoint.
type ServerInfo struct {
	ID       string
	Name     string
	Endpoint string
	Prefixes []string
}
